import 'package:flutter/material.dart';
import 'package:hexcolor/hexcolor.dart';

List<Color> colorsList = [
  Colors.red,
  Colors.blue,
  Colors.green,
  Colors.yellow,
  Colors.orange,
  Colors.purple,
  Colors.pink,
  Colors.teal,
  Colors.tealAccent,
  HexColor('#824e4a'),
  HexColor('#eb10d8'),
  Colors.red,
  Colors.blue,
  Colors.green,
  Colors.yellow,
  Colors.orange,
  Colors.purple,
  Colors.pink,
  Colors.teal,
  Colors.tealAccent,
  HexColor('#824e4a'),
  HexColor('#eb10d8'),Colors.red,
  Colors.blue,
  Colors.green,
  Colors.yellow,
  Colors.orange,
  Colors.purple,
  Colors.pink,
  Colors.teal,
  Colors.tealAccent,
  HexColor('#824e4a'),
  HexColor('#eb10d8'),Colors.red,
  Colors.blue,
  Colors.green,
  Colors.yellow,
  Colors.orange,
  Colors.purple,
  Colors.pink,
  Colors.teal,
  Colors.tealAccent,
  HexColor('#824e4a'),
  HexColor('#eb10d8'),Colors.red,
  Colors.blue,
  Colors.green,
  Colors.yellow,
  Colors.orange,
  Colors.purple,
  Colors.pink,
  Colors.teal,
  Colors.tealAccent,
  HexColor('#824e4a'),
  HexColor('#eb10d8'),

];
